import { PERMISSIONS, Permission } from '@/shared/constants/permissions';
import { RoleName } from '@/shared/constants/roles';

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  super_admin: [
    // All permissions (governance + operational + self-service)
    ...Object.values(PERMISSIONS),
  ],
  admin: [
    // Operational permissions (no governance)
    PERMISSIONS.VIEW_ALL_CAMPERS,
    PERMISSIONS.VIEW_ALL_APPLICATIONS,
    PERMISSIONS.REVIEW_APPLICATION,
    PERMISSIONS.VIEW_ALL_MEDICAL_RECORDS,
    PERMISSIONS.MANAGE_CAMPS,
    PERMISSIONS.MANAGE_SESSIONS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.CREATE_CONVERSATION,
    PERMISSIONS.SEND_MESSAGE,
    PERMISSIONS.MODERATE_MESSAGES,
    PERMISSIONS.DELETE_ANY_CAMPER,
    PERMISSIONS.DELETE_APPLICATION,
    PERMISSIONS.DELETE_MEDICAL_RECORD,
  ],
  parent: [
    // Self-service permissions
    PERMISSIONS.VIEW_OWN_CAMPERS,
    PERMISSIONS.CREATE_CAMPER,
    PERMISSIONS.UPDATE_OWN_CAMPER,
    PERMISSIONS.DELETE_OWN_CAMPER,
    PERMISSIONS.VIEW_OWN_APPLICATIONS,
    PERMISSIONS.CREATE_APPLICATION,
    PERMISSIONS.UPDATE_OWN_APPLICATION,
    PERMISSIONS.SIGN_APPLICATION,
    PERMISSIONS.VIEW_OWN_MEDICAL_RECORDS,
    PERMISSIONS.CREATE_MEDICAL_RECORD,
    PERMISSIONS.UPDATE_MEDICAL_RECORD,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.DOWNLOAD_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.CREATE_CONVERSATION,
    PERMISSIONS.SEND_MESSAGE,
  ],
  medical: [
    // Read-only medical permissions
    PERMISSIONS.VIEW_ALL_MEDICAL_RECORDS,
  ],
};

export type { Permission };
